openapi: 3.0.0
info:
  version: 1.0.0
  title: GoSwift User Microservice
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080/v1'
  - url: 'https://localhost:8443/v1'

paths:
  /load:
    get:
      summary: Loads 10 users into DB
      operationId: loadUsers
      tags:
        - users
      responses:
        '200':
          description: successfully loaded
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{userId}:
    get:
      summary: Get specific user
      operationId: getUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: User based on UserId
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
